# See https://docs.rs/ratatui/latest/ratatui/style/enum.Color.html

top_bar_background = "#443222"
top_bar_foreground_selected = "#e5c07b"

foreground = "#d19a66"
foreground_selected = "black"
foreground_secondary = "white"

background = "black"
background_selected = "#d19a66"
background_selected_blur = "#865528"

search = "red"
