name: Cargo Release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  release_linux:
    name: Release Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
          chmod a+x rustup.sh
          ./rustup.sh -y

      - run: rustc --print target-list
      - run: rustc --target=x86_64-unknown-linux-gnu --print target-cpus

      - run: sudo apt-get update && sudo apt-get install libasound2-dev

      - run: cargo build --locked --release --target x86_64-unknown-linux-gnu
      # - run: cargo build --locked --release --target x86_64-unknown-linux-musl # can't. cpal needs libc.
#      - run: tar --version
      - run: pwd
      - run: tree target/x86_64-unknown-linux-gnu -L 2
#      - run: tar czf jolteon.tar.gz --directory=./target/x86_64-unknown-linux-gnu/release jolteon
      - uses: actions/upload-artifact@v4
        with:
#          name: jolteon-x86_64-unknown-linux-gnu.tar.gz
          name: jolteon-x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/jolteon
          compression-level: 0
