name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    name: "${{ matrix.platform.os }} ${{ matrix.platform.target }}"
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu  }
          - { os: macos-latest , target: x86_64-apple-darwin       }
          - { os: macos-latest , target: aarch64-apple-darwin      }
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
          chmod a+x rustup.sh
          ./rustup.sh -y

      - run: rustc --print target-list
      - run: rustup target add ${{ matrix.platform.target }}
      - run: rustc --target=${{ matrix.platform.target }} --print target-cpus

      - run: sudo apt-get update && sudo apt-get install libasound2-dev
        if: ${{ matrix.platform.os == 'ubuntu-latest' }}

      - run: cargo check --locked --target ${{ matrix.platform.target }}
      - run: cargo test --locked --target ${{ matrix.platform.target }}
