name: Cargo Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test_linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#      - run: curl --version
#      - run: type curl
#      - run: type sh

      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
          chmod a+x rustup.sh
          ./rustup.sh -y

      - run: rustup install nightly
      - run: rustup override set nightly
      - run: sudo apt-get update && sudo apt-get install libasound2-dev

      - run: cargo check
      - run: cargo test
      - run: cargo build
      - run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: target/release/jolteon
